### ISSUE TITLE
DeprecationWarning: `context.fix` is being deprecated with stylelint 16.8.2

### ISSUE THREAD

**Issue by sebbayer** [AndyOGo/stylelint-declaration-strict-value#379]
With the latest stylelint version 16.8.2 I get lots of deprecation warnings because `context.fix` is being deprecated:

> (node:4037) [stylelint:005] DeprecationWarning: `context.fix` is being deprecated.
Please pass a `fix` callback to the `report` utility of "scale-unlimited/declaration-strict-value" instead.

See 16.8.2 changelog: https://stylelint.io/changelog/
And the PR: https://github.com/stylelint/stylelint/pull/7895

**Comment by AndyOGo** [comment]
Thx a lot.
https://stylelint.io/developer-guide/rules/#add-autofix

**Comment by silverwind** [comment]
FYI, with [Stylelint v16.9.0](https://github.com/stylelint/stylelint/releases/tag/16.9.0), a workaround is available via `NODE_OPTIONS=--no-deprecation`to suppress the deprcation warnings.

**Comment by kliehm** [comment]
Yeah, so it's deprecated. As an end user, I call it with the CLI and the `--fix` suffix. Is there anything else I can do to make this annoying message go away?

**Comment by silverwind** [comment]
> Is there anything else I can do to make this annoying message go away

You could downgrade stylint to 16.8.1, before the deprecation was introduced.

**Comment by kliehm** [comment]
@silverwind @AndyOGo I don't understand, aren't you going to fix this? Or did you already fix it? If so, i which release?

**Comment by AndyOGo** [comment]
@kliehm 
You find the answer to your questions in the release notes of stylelint.

> Fixed: honour Node.js `--no-deprecation` flag for rule deprecation warnings (https://github.com/stylelint/stylelint/pull/7943) (@Mouvedia).
https://github.com/stylelint/stylelint/releases/tag/16.9.0

Thank you.

**Comment by AndyOGo** [comment]
Thank you for your opinion.

Please understand that this is a **deprecation**, it's not a bug or something broken.
You get a warning and `styelint` provides a way to hide those - the new API will be enforced in the next major version and then this plugin will update.

> (computing) the fact of a software feature becoming [outdated](https://www.oxfordlearnersdictionaries.com/definition/english/outdated) and best avoided because it has been replaced with something newer
https://www.oxfordlearnersdictionaries.com/definition/english/deprecation

**Comment by kliehm** [comment]
> Thank you for sharing you idea.
> 
> Please understand that this is a **deprecation**, it's not a bug or something broken. You get a warning and `styelint` provides a way to hide those - the new API will be enforced in the next major version and then this plugin will update.
> 
> > (computing) the fact of a software feature becoming [outdated](https://www.oxfordlearnersdictionaries.com/definition/english/outdated) and best avoided because it has been replaced with something newer
> > https://www.oxfordlearnersdictionaries.com/definition/english/deprecation

I know what deprecation means. It also means that you need to change something so that it's still compatible in the future. You can't just sit it out. 😄

**Comment by AndyOGo** [comment]
@kliehm next time before you spam an issue thread.

Please make sure to carefully read and understand the official documentation and release notes.
Then please make sure that you are able to evaluate the importance of different aspects of software engineering.
Last but not least work on your social competence.

Thank you.

**Comment by AndyOGo** [comment]
@kliehm No, that is incorrect.

Your question has already been answered two ways.

1. I added a `maintance` label on Aug 19
2. That [comment](https://github.com/AndyOGo/stylelint-declaration-strict-value/issues/379#issuecomment-2317074368) on Aug 29 reference the styleint release notes and the official way to deal with this until the `context.fix` API is completelly removed

Frankly, you have not accomplished a senior level in programming - that becomes obvious by your lack of understand of these clear and simple informations.

**Comment by kliehm** [comment]
> @kliehm No, that is incorrect.
> 
> Frankly, you have not accomplished a senior level in programming - that becomes obvious by your lack of understanding of these clear and simple information.

Please refrain from depreciating people whom you don't know, and stick to the topic.

**Comment by AndyOGo** [comment]
@kliehm 
Why is your behavior okay?
Why is your cynical and derisive comment acceptable?

> You can't just sit it out. 😄

To me it's not acceptable and I insist that you

1. make sure to read and understand official documentation to improve your technical competence
2. work on your manners and your social competence and treat social people with respect and dignity

**Comment by kliehm** [comment]
I don't need your advice on technical competence. That is beyond your knowledge and competence to give such advice. You don't appear to be very social competent yourself. I hope your future employer reads this embarrassing dialogue.

**Comment by AndyOGo** [comment]
@kliehm
Alright, I got that.

What are log levels?
What is verbosity?
What are syntactical and lexical grammars?
What makes a grammar context free?
What is and how to read the Backus–Naur form?
What is the visitor pattern?
Did you study the syntax specifications of CSS, SASS, Less and other CSS-like grammars?

You know the 101 of them by heart?

Well, you called me ignorant?
To carefully study, understand and apply the above one has to be quite the opposite of ignorant.

Maybe you don't realize how invalidating that term really is.

> 1. (often disapproving) not having or showing much knowledge or information about things; not educated
> 2. not having any knowledge or information about a particular thing
https://www.oxfordlearnersdictionaries.com/definition/english/ignorant

Or you just don't know how much work goes into open source software.
This is a social project, free of charge.

**Comment by ScorpAL** [comment]
OMG... Stop arguing please.

```
...
"stylelint": "^16.10.0",
"stylelint-config-clean-order": "^6.1.0",
"stylelint-config-standard-scss": "^13.1.0",
"stylelint-declaration-strict-value": "^1.10.6",
"stylelint-use-logical-spec": "^5.0.1",
...
```

I still see
```
...
(node:16392) [stylelint:005] DeprecationWarning: `context.fix` is being deprecated.
Please pass a `fix` callback to the `report` utility of "scale-unlimited/declaration-strict-value" instead.
(node:16392) [stylelint:005] DeprecationWarning: `context.fix` is being deprecated.
Please pass a `fix` callback to the `report` utility of "scale-unlimited/declaration-strict-value" instead.
(node:16392) [stylelint:005] DeprecationWarning: `context.fix` is being deprecated.
Please pass a `fix` callback to the `report` utility of "scale-unlimited/declaration-strict-value" instead.
...
```

just when `scale-unlimited/declaration-strict-value` config added.
Like:

```
'scale-unlimited/declaration-strict-value': [
    ['/color$/', 'fill'],
    {
        expandShorthand: true,
        ignoreValues: ['transparent', 'currentcolor', 'inherit'],
        autoFixFunc: autoFixFunc,
        disableFix: true
    }
]
```
not matter with or without `autoFixFunc` or `disableFix: true`

Firstly I thinking that `disableFix: true` should help me,

While you continue fighting, for me better to comment this config (or disable 'scale-unlimited/declaration-strict-value') rather then downgrading for `styleint`.

**Comment by AndyOGo** [comment]
@ScorpAL 

Stylelint offers a workaround to suppress those deprecation warnings.
This has been pointed out first by @silverwind 

> FYI, with [Stylelint v16.9.0](https://github.com/stylelint/stylelint/releases/tag/16.9.0), a workaround is available via `NODE_OPTIONS=--no-deprecation` to suppress the warnings.

Then a second time by myself.

> @kliehm You find the answer to your question in the release notes of stylelint.
> 
> > Fixed: honour Node.js `--no-deprecation` flag for rule deprecation warnings ([stylelint/stylelint#7943](https://github.com/stylelint/stylelint/pull/7943)) (@Mouvedia).
> > https://github.com/stylelint/stylelint/releases/tag/16.9.0
> 
> Thank you.

---

The migration will happen with the next major version of stylelint.

**Comment by ScorpAL** [comment]
@AndyOGo thanks.

I have used `--quiet-deprecation-warnings` temporarily in my `package.json` scripts

```
"scripts": {
    ...
    "lint:css": "stylelint src/**/*.{css,scss} --quiet-deprecation-warnings",
    ...
},
```

https://stylelint.io/user-guide/options#quietdeprecationwarnings

**Comment by myovchev** [comment]
I was forced to completely disable to rule in our stylelint config package because:
- I don't want to add flags to dozens of packages + customers using it.
- I don't want to do the same once the problem is resolved
- I don't want to silence deprecation warnings on everything (if using NODE_OPTIONS). 

Why was important to get rid of the warnings:
- It nearly breaks CI (large codebases).
- It's extremely slow and annoying when it runs in local development.

I'm not aware of the context so I can't participate in the discussion. My desire is to use a package and get a clear but useful solution - a simple configuration, that solves a problem in hand. The simple principle that I'm following is: the fellow dev didn't do anything wrong (no misconfiguration or stupid code), so everything that comes as a problem after that and is a pain. is something that has to be resolved in a satisfactory for everyone way.

**Comment by AndyOGo** [comment]
Stylelint offers multiple ways to disable their deprecation warnings.
You find that information in different parts of their documentation (I strongly advise to read the full documentation so that you get the full concept of it).

1. via [`quietDeprecationWarnings` Option](https://stylelint.io/user-guide/options/#quietdeprecationwarnings)
   **Attention:** please note that at the very top it is defined how those option may be used
   > Options shared by the:
   > - [CLI](https://stylelint.io/user-guide/cli)
   > - [Node.js API](https://stylelint.io/user-guide/node-api)
   > - [PostCSS plugin](https://stylelint.io/user-guide/postcss-plugin)
   > You can use some of these options in the [configuration object](https://stylelint.io/user-guide/configure).
2. via their [CLI's `--quiet-deprecation-warnings` arg](https://stylelint.io/user-guide/cli#--quiet-deprecation-warnings)
3. via [`NODE_OPTIONS=--no-deprecation`](https://github.com/stylelint/stylelint/releases/tag/16.9.0) environment variable
   - this is based upon the official Node [`NODE_OPTIONS=options...`](https://nodejs.org/api/cli.html#node_optionsoptions)

**Comment by AndyOGo** [comment]
## Update

I just released an [unsafe monkey patch](https://en.wikipedia.org/wiki/Monkey_patch#Pitfalls) of node's [`process.emitWarning`](https://nodejs.org/api/process.html#processemitwarningwarning-options) API as [`v1.10.7`](https://github.com/AndyOGo/stylelint-declaration-strict-value/compare/v1.10.6...v1.10.7) to suppress any stylelint related deprecation warnings in relation to this plugin.

For further information why this approach was choosen, please see the ticket at stylint:
https://github.com/stylelint/stylelint/issues/8249

Further more node recently added [`--disable-warning`](https://nodejs.org/api/cli.html#--disable-warningcode-or-type) command-line option to give users more fine-grained control of which warnings to disable.

I will leave this ticket open until the next major version of stylelint is released and the `context.fix` is completely removed (including this monkey patch).

**Comment by ahenriksen-inferno** [comment]
> ## Update
> I just released an [unsafe monkey patch](https://en.wikipedia.org/wiki/Monkey_patch#Pitfalls) of node's [`process.emitWarning`](https://nodejs.org/api/process.html#processemitwarningwarning-options) API as [`v1.10.7`](https://github.com/AndyOGo/stylelint-declaration-strict-value/compare/v1.10.6...v1.10.7) to suppress any stylelint related deprecation warnings in relation to this plugin.
> 
> For further information why this approach was choosen, please see the ticket at stylint: [stylelint/stylelint#8249](https://github.com/stylelint/stylelint/issues/8249)
> 
> Further more node recently added [`--disable-warning`](https://nodejs.org/api/cli.html#--disable-warningcode-or-type) command-line option to give users more fine-grained control of which warnings to disable.
> 
> I will leave this ticket open until the next major version of stylelint is released and the `context.fix` API is completely removed (including this monkey patch).

@AndyOGo - Thank you very much for the monkey patch release! 🐵 For my needs, this approach works much better, and I appreciate you taking the time to implement it.

**Comment by myovchev** [comment]
@AndyOGo Thanks for the effort. I completely understand and share the hesitance to introduce anti-patterns in your code. I did follow the discussion you linked here and I do like the argumentation [in this comment](https://github.com/stylelint/stylelint/issues/8249#issuecomment-2564751976). I could write a whole article on "Why deprecation warnings that can't be muted are evil". And when I say "can't be muted" I include those that can be muted on a process level. Why? Because in some cases we don't have control over the process. Think of shared configs between hundreds of projects (or even bigger number when it's a popular public config). We need a configuration control over the warnings. It's even worst when the end user doesn't understand (and don't need to understand) why this warning is there in a first place (internals should be kept internal). 

With that said, without knowing any internal logic, I'd say this is a problem of how stylelint introduces warnings, the plugin authors and end users are bearing the consequences. Also it looks like that the stylelint community wants and will find a solution in the near future (deducing from what I'm reading in referenced discussions). These are all good things. 

This is not a unique for stylelint community problem. Not so long ago there was a similar problem with a Sass release that did put the world on fire. The initial response of the developers was "this is the right thing to do, it should be in your face". This changed short after and now I'm able to mute warnings per ID (unique name) directly in my Vite config. 

Why this all matters? Muting a warning is a part of a the contract between a vendor (a package) and user (a developer). There are clear responsibilities and a safety protocol. Explicit opt-out of a specific deprecation warning means "I understand the implications". Semver helps me handle it properly. I'm aware that I'm stuck with a major version. I can also plan what is the right time to fix my code based on the expected effort.  

I understand the position of a plugin author is unique, because all kind of public API, BC, FC constraints. I'm grateful that you took an extra mile in an attempt to fix this mess. Cheers!

**Comment by Donov4n** [comment]
Does the monkey patch still work? In my case, the message is displayed because the monkey patch tries to check the presence of the package name in `message` when it only appears in `options.detail` :

---

In my StyleLint 16.14.1, I have the following arguments for `emitWarnings`:

```
[
  '`context.fix` is being deprecated.',
  {
    type: 'DeprecationWarning',
    code: 'stylelint:005',
    detail: 'Please pass a `fix` callback to the `report` utility of "scale-unlimited/declaration-strict-value" instead.'
  }
]
```

So the monkey-patch should probably updated to:

```patch
if (
-     message &&
-     typeof message === 'string' &&
-     message?.includes(ruleName) &&
      options &&
      typeof options === 'object' &&
+     options?.detail?.includes(ruleName) &&
      options?.type === 'DeprecationWarning' &&
      options?.code?.startsWith(STYLELINT_DEPRECATION_WARNING_PREFIX)
) {
  return;
}
```

**Comment by AndyOGo** [comment]
I just released a fix of the [unsafe monkey patch](https://en.wikipedia.org/wiki/Monkey_patch#Pitfalls) of node's [`process.emitWarning`](https://nodejs.org/api/process.html#processemitwarningwarning-options) API as [`v1.10.8`](https://github.com/AndyOGo/stylelint-declaration-strict-value/compare/v1.10.7...v1.10.8)

**Comment by flavio-marchi-exxas** [comment]
> will happen with the next major version of stylelint.

When will this happen? The error still shows today with the latest version.

**Comment by AndyOGo** [comment]
Closed by #388 / #389 

It's released with [v1.11.0](https://github.com/AndyOGo/stylelint-declaration-strict-value/releases/tag/v1.11.0) holding these [changes](https://github.com/AndyOGo/stylelint-declaration-strict-value/blob/master/CHANGELOG.md#1110-2026-02-17).
